### PR TITLE
Add stan code changes for missing data model

### PR DESCRIPTION
**Pull request by seabbs**
This PR is a partial replacement for #64 and builds on top of #106 with the required stan model changes. It cannot be merged until #106 has been merged. It implements the stan code changes suggested in #43.

### CODE REVIEW

**Comment by seabbs** [comment]
@adrian-lison just an FYI but the redesign work is getting a bit out of hand and leading to a fairly broad change in the names of variables (to make it easier to automate in the R code but then requires stan changes to keep consistency). That means this PR may be easier if we rebase once that is done and go directly for a formula interface implementation. 

That being said if you have some time and want to work on this the thing that will not need updating (and is the trickest bit) is adding the two likelihood fns (i.e the one currently in `develop` and the missing data one we need here that is parallel over groups).

**Comment by adrian-lison** [comment]
As discussed, we need to make the model save for `dmax>=t`. Since literally _no_ observations with missing reference date can be used in the likelihood in such a case, it probably makes sense to check for this in the beginning (transformed data) and either 1) reject (aka please use the non-missingness model version or a longer time window) or 2) switch to the non-missingness model automatically, ignoring all missingness data and print a warning.
The good news is that in both cases we only need a simple check in the beginning and no complicated `min` functions in the missingness likelihood as it doesn't make sense anyway, so this is an easy task. Should be done once we have the two likelihoods and the optional switch implemented:

- [ ] Handle `dmax>=t` case.

**Comment by adrian-lison** [comment]
Further ToDos
- [ ] Change missingness model parts to log scale
- [ ] Implement two different likelihood functions
- [ ] Implement matrix-based version for obs in missingness likelihood
- [ ] Implement group-wise within-chain parallelisation for missingness likelihood

**Comment by seabbs** [comment]
Shall I do another conflicts PR for this and add in the new variables from `enw_missing()`?

**Comment by seabbs** [comment]
Just noting I have started to fix the merge issues introduced in `0.1.0`. I will have something tomorrow I think.

**Comment by seabbs** [comment]
had a go at this but may have done more harm than good. See #133 where thinking that doing some more work on modularising the observation model in `develop` may help in making this addition (and in making future additions easier).

**Comment by seabbs** [comment]
I might role back the work I did on this yesterday as I was losing my mind it appears!

**Comment by adrian-lison** [comment]
I am sorry this became such a mess. Might have not been the best timing with this PR vs. the other breaking changes.

**Comment by adrian-lison** [comment]
Regarding the matrix-based version for obs in the missingness likelihood, I suggest to do it roughly like I did it here:
https://github.com/adrian-lison/nowcast-transmission/blob/main/code/models/model/likelihood_reported.stan

That is, have a matrix
`matrix[D, T] expected_obs_miss = rep_matrix(0, D, T);`

then, for every time `t` (assuming we are in one group at the moment)
`expected_obs_miss[1:min(T-t,D), t] = expected_obs_all + alpha1m_log[t];`

And then, after the loop, something like this:
```
  // reshape reporting triangle by date of report, leaving out left-truncated dates
  matrix[D, T-D] expected_obs_miss_rep
    = reporting_triangle_by_report(expected_obs_miss, D);
  // compute log expected cases with missing occurrence for each date of report
  vector[T-D] expected_obs_miss_rep_vec;
  for (i in 1:(T-D)) {
    expected_obs_miss_rep_vec[i] = log_sum_exp(col(expected_obs_miss_rep,i));
  }
```
The function `reporting_triangle_by_report` I have implemented here: https://github.com/adrian-lison/nowcast-transmission/blob/main/code/models/functions/reporting_triangles.stan (might need some tweaking because of the different max_delay definitions).

Then we can use `expected_obs_miss_rep_vec` in a vectorized negative binomial likelihood.

**Comment by seabbs** [comment]
Closing in favour of #138 and #147

**Pull request closed without merging**
