### PR TITLE
address match.args change

### PR DESCRIPTION
**Pull request by pearsonca**
Addresses #156, with the exception of some esoteric `match.arg` uses

### CODE REVIEW

**Comment by pearsonca** [comment]
I can update that part. Is there also place more broadly to document the preferred use of `match.arg`? Something style-guide ish?

**Comment by seabbs** [comment]
I think perhaps the part that says following the style of the code may cover it? We don't have a very detailed style document yet where this would live (probably scare people with detail if it went in the more general one we do have).

**Comment by pearsonca** [comment]
alright; i think this too specific for the current level of discussion in CONTRIBUTING, so i've just noted in the NEWS write up.

**Comment by pearsonca** [comment]
aside: bit surprised that tweak to NEWS file only triggers all the check actions. anyway to exclude changes to certain files (e.g. NEWS, CONTRIBUTING, LICENSE come to mind) from triggering that?

**Review by seabbs — APPROVED** [review]
LGTM. ❤️

**Pull request merged**
