### PR TITLE
future-proof array declarations

### LINKED ISSUE #74: Warnings about deprecated array declarations
Compiling the model throws warnings about deprecated array declarations.

```r
> library(epinowcast )
> model <- enw_model(threads = TRUE)
Compiling Stan program...
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/zero_truncated_normal.stan', line 8, column 32, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 5, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 1, column 14, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 1, column 47, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 1, column 58, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v
830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 1, column 68, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 2, column 14, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 2, column 32, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 2, column 42, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.s
tan', line 2, column 52, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 3, column 43, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a type is deprecated and will be
    removed in Stan 2.32.0. Instead use the array keyword before the type.
    This can be changed automatically using the auto-format flag to stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/include_1/stan/functions/obs_lpmf.stan', line 9, column 2, included from
'/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 7, column 0: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 16, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 17, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before 
the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 18, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 19, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 20, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 23, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 24, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.s
tan', line 25, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    
type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 28, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 37, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 49, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 50, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 51, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', li
ne 52, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 53, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 54, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 55, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 68, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 69, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the

    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 70, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 88, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 178, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 180, column 2: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
Warning in '/var/folders/gd/x84kkjzd6bn9rlf3f2v830c00000gp/T/Rtmpb3d2EJ/model-10e86bd5a0c6.stan', line 186, column 4: Declaration
    of arrays by placing brackets after a variable name is deprecated and
    will be removed in Stan 2.32.0. Instead use the array keyword before the
    type. This can be changed automatically using the auto-format flag to
    stanc
```

### PR DESCRIPTION
**Pull request by sbfnk**
Fixes #74

### CODE REVIEW

**Comment by seabbs** [comment]
We've sat on this because of concerns about back compatibility with `rstan` (and in particular the expose function tooling). i.e #39

That being said can't stand these warnings forever so will have to update at some point. I am happy for that to be now and to just accept no longer being able to test using `rstan` if this is the case.

The other option is to update `enw_example` to pass the required options so that `cmdstan` auto-reformats these kind of things at readme. This would keep backwards compatibility whilst also stopping the warnings. Downside is this would split code being run from code you seen when you look at the source which isn't ideal.

**Comment by seabbs** [comment]
> moment the code isn't compatible with rstan (

The functions are compatible and this is what lets them be tested (as can use `expose_stan`) to test them independtly of the model. 

You are right in the sense that the model can't be run with `rstan` and at this point I don't think that is worth having as they seem to have largely given up updating. The pain point for users is having to compile the model themselves (and no ability to give them a pre-built binary of the model). 

User wise for this though I am thinking the target market needs to be technical enough for compilation etc to not be a major hurdle.

**Comment by sbfnk** [comment]
Not saying it's the most elegant solution but if the array syntax is the sticking point could always rely on something like this
https://github.com/epiforecasts/inc2prev/blob/577d0e4b743c3d3ef511562af32142579924fa45/R/simulate.R#L15

**Comment by seabbs** [comment]
Yes good point. This would be the reverse of converting to `cmdstan` for inference and be less obvious to the user so probably nicer.

**Comment by sbfnk** [comment]
(the regex would need to be updated as at the moment it only works for `array[]` and is quite sensitive to where exactly there are spaces are put - but shouldn't be too hard)

**Comment by seabbs** [comment]
I've updated `expose_stan_fns` to deal with profiling terms and array terms. Still has some unfortunately issues with the custom likelihood functions. On top of the array warnings I also see an include paths warning but this may be local to my set-up. I haven't been able to resolve this so will just keep an eye on

**Pull request merged**
