### PR TITLE
Use inherits to test class

### PR DESCRIPTION
**Pull request by Bisaloo**
As recommended in https://developer.r-project.org/Blog/public/2019/11/09/when-you-think-class.-think-again/

### CODE REVIEW

**Review by seabbs — COMMENTED** [review]
Thanks for this Hugo, this is a good spot. 

I've retargeted this at `develop` as we are operating a two-branch process (as we can't go to CRAN due to `cmstanr` for our releases and people automatically used `main`). 

If you have a chance could you also add a [news update + yourself as a contributor](https://github.com/epiforecasts/epinowcast/blob/main/CONTRIBUTING.md)? If possible also fleshing out the PR message would help people to keep track of development.

**Comment by seabbs** [comment]
Just pinging this. I am totally happy to do the finishing bits mentioned above and then merge if no time etc. Also very happy to wait as clearly no rush.

**Comment by Bisaloo** [comment]
> I've retargeted this at develop as we are operating a two-branch process (as we can't go to CRAN due to cmstanr for our releases and people automatically used main).

Does this mean the CONTRIBUTING guide should be slightly rephrased? It currently states:

> We use a develop/ main workflow so please target major changes to the develop branch and minor changes to the main branch. 

This looks like a very minor change.

> If you have a chance could you also add a [news update + yourself as a contributor](https://github.com/epiforecasts/epinowcast/blob/main/CONTRIBUTING.md?rgh-link-date=2022-08-08T11%3A05%3A46Z)? If possible also fleshing out the PR message would help people to keep track of development.

I've amended my commit with a more detailed commit message, added an entry in the changelog & fixed the conflict. I don't think this change warrants adding myself as a contributor.

**Comment by seabbs** [comment]
> This looks like a very minor change

It could potentially be updated. Minor changes was really supposed to mean typos, documentation rephrasing etc.

**Review by seabbs — APPROVED** [review]
LGTM - thanks again for this.

**Pull request merged**
